version: "3.8"
 
services:
  chatbot:
    build: .
    image: chatbot-linux:latest
    container_name: chatbot_linux
    # Permite que el contenedor acceda a la pantalla del host (necesario para Tkinter)
    environment:
      - DISPLAY=172.25.144.1:0.0
    volumes:
      # Volumen para que los cambios en base_datos.json sean persistentes
      - ./src/base_datos.json:/app/base_datos.json
      # Acceso a X11 para mostrar la ventana gráfica
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    restart: "no"
 